### ISSUE TITLE
Periodic freezes/lag

### ISSUE THREAD

**Issue by isomeras** [Freebi85/Explorico_Classic#1]
On single player, game will periodically freeze up to the point of not responding for several seconds. This doesn't happen so often as to render the pack unplayable, but becomes a hassle from time to time and seems likely to get the player killed unfairly at some point.

**Comment by isomeras** [comment]
Update: it got the player killed unfairly at some point. Just in any average fight.

**Comment by Freebi85** [comment]
On the one hand, this is quite possible because there are still many experimental mods that are replaced or removed from time to time. The current update was not particularly performance friendly but the next one is on the way 👍 
But basically the first few minutes after loading the world, it may well freeze periodically a few times. After that, however, it should work. Assuming that you have at least 8 - 10 GB ram allocated to the launcher. 
Whereas 1.16 is much more intensive for my PC and I personally had to give 10 to be able to play smoothly. This can vary from system to system of course.

Since this can be classified more under technical support, I recommend to visit our discord server and gonna close this. There you can consult with other players to improve performance and efficiency, and you can also see what's going on with the pack^^

Here I deal more with issues around recipes, missing integrations in machines, suggestions and stuff like that^^

Cheers 🍺
