### ISSUE TITLE
Abyss - Stuck in Void Dimension at Day 2!?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Explorico_Classic#20]
I seem to have gotten stuck in the Void dimension you enter at sleep time as soon as day 2 of my playthrough.

There appears to be no "trigger" that sends me back to the overworld, and there's nothing coming up in my current searching.

Please advise.
![2021-09-05_17 48 57](https://user-images.githubusercontent.com/10191173/132143291-0da1837b-0f2b-48ed-82ab-7d63b9300196.png)

**Comment by Danekjovax** [comment]
I'll add that there's an assumed "RTFM" from the mod author that there must be info in the Abyss 2 guidebook that may speak about getting "out" of these dream worlds, and I see that book included in the starter pack, but when I try to open it I get this error:
![image](https://user-images.githubusercontent.com/10191173/132143960-dc84bf81-a6f2-490b-bddd-c69e449c98a9.png)

So assuming the book loaded the data, perhaps I could find a remedy in-game to get out of this blasted dimension.

Until then, I'd heavily advise to allow cheats and liberally use /home or /spawn to exit these dimensions.

**Comment by Freebi85** [comment]
After I was in their discord, it turned out that the dream function is still heavily bugged and there is sometimes no way out without TP. 
For this reason I uploaded a hotfix which downgraded abyss before the dream thingy was added and the dimension can be reached regularly through its own mod portal.
The Guidebook probably not even exists yet on this version.

**Comment by Danekjovax** [comment]
I'd be ok to disable this from the modpack.
